language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

addons:
   code_climate:
     repo_token: a69242268fba4d9eb660619cd6ed8669ca8c9ae4b55311660b8af822e9187178
